//go:build ignore

// Command gen_logo (run via internal/tui/logo.go's go:generate directive)
// decodes the checked-in assets/liam.png into logo_gen.go's logoTop/
// logoBottom block-art data: a fixed cols x (rows*2) grid, box-averaged
// down from the source image, then each half-block cell classified as
// transparent or whichever of liam's two fixed brand colors
// (logoColorDark/logoColorLight, defined in logo.go) it's nearest to. Only
// the standard library's image/image/png is used, per CODING_STANDARDS.md's
// dependency bar — no third-party image-processing package.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"image"
	_ "image/png"
	"log"
	"os"
)

// cols/rows are the block-art's fixed output size: cols half-block columns
// by rows half-block rows (each row samples 2 source pixel rows). Chosen by
// hand (see issue #169's PR) as the largest grid that still reads as a
// recognizable, compact silhouette beside 3 lines of banner text — much
// larger and the shape washes out into noise at typical terminal fonts,
// much smaller and it stops being recognizable at all.
const (
	cols = 20
	rows = 9
)

// alphaThreshold is the un-premultiplied alpha (0-1) below which a sampled
// cell half is treated as fully transparent rather than classified into one
// of the two brand colors — the source PNG's silhouette is mostly
// transparent background plus antialiased edges, and a low threshold would
// pick up those edge pixels as noise around the shape.
const alphaThreshold = 0.35

const (
	logoColorDarkR, logoColorDarkG, logoColorDarkB    = 0x25, 0x19, 0x10
	logoColorLightR, logoColorLightG, logoColorLightB = 0x7D, 0x62, 0x49
)

// This file is compiled standalone via `go run gen_logo.go` (its
// "//go:build ignore" tag excludes it from package tui entirely), so it
// can't import logo.go's logoPixel/logoTransparent/logoDark/logoLight —
// these mirror those byte values exactly; keep the two in sync by hand if
// either changes.
const (
	pixelTransparent byte = ' '
	pixelDark        byte = 'D'
	pixelLight       byte = 'L'
)

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	f, err := os.Open("../../assets/liam.png")
	if err != nil {
		return fmt.Errorf("gen_logo: open source image: %w", err)
	}
	defer f.Close()

	img, _, err := image.Decode(f)
	if err != nil {
		return fmt.Errorf("gen_logo: decode source image: %w", err)
	}

	top := make([]string, rows)
	bottom := make([]string, rows)
	for r := 0; r < rows; r++ {
		top[r] = sampleRow(img, r, 0)
		bottom[r] = sampleRow(img, r, 1)
	}

	var buf bytes.Buffer
	fmt.Fprint(&buf, "// Code generated by go:generate from assets/liam.png; DO NOT EDIT.\n\n")
	fmt.Fprint(&buf, "package tui\n\n")
	fmt.Fprint(&buf, "// logoTop and logoBottom are liam's block-art logo (issue #169), decoded\n")
	fmt.Fprint(&buf, "// from assets/liam.png by gen_logo.go. Each string is one terminal row's\n")
	fmt.Fprint(&buf, "// fixed-width sequence of logoPixel classifications (see logo.go), top and\n")
	fmt.Fprint(&buf, "// bottom paired per half-block character cell.\n")
	writeStringSlice(&buf, "logoTop", top)
	writeStringSlice(&buf, "logoBottom", bottom)

	// format.Source (rather than hand-tracked blank-line bookkeeping above)
	// guarantees gofmt-clean output, matching every other file in the repo.
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gen_logo: gofmt generated source: %w", err)
	}
	if err := os.WriteFile("logo_gen.go", src, 0o644); err != nil {
		return fmt.Errorf("gen_logo: write logo_gen.go: %w", err)
	}

	return nil
}

// sampleRow renders block-art row r's half (0 = top, 1 = bottom) as a
// cols-length string of logoPixel bytes.
func sampleRow(img image.Image, r, half int) string {
	b := img.Bounds()
	w, h := b.Dx(), b.Dy()
	pixelRows := rows * 2

	y0 := b.Min.Y + (r*2+half)*h/pixelRows
	y1 := b.Min.Y + (r*2+half+1)*h/pixelRows

	buf := make([]byte, cols)
	for c := 0; c < cols; c++ {
		x0 := b.Min.X + c*w/cols
		x1 := b.Min.X + (c+1)*w/cols
		buf[c] = classify(avgRegion(img, x0, x1, y0, y1))
	}
	return string(buf)
}

// avgRegion averages the un-premultiplied color+alpha of every pixel in
// [x0,x1)x[y0,y1), weighted by each pixel's own alpha — a fully-transparent
// pixel contributes no color, only "no coverage" to the alpha average.
func avgRegion(img image.Image, x0, x1, y0, y1 int) (r, g, bl, a float64) {
	var sr, sg, sb, sa, n float64
	for y := y0; y < y1; y++ {
		for x := x0; x < x1; x++ {
			pr, pg, pb, pa := img.At(x, y).RGBA()
			af := float64(pa) / 0xffff
			if pa > 0 {
				sr += float64(pr) / float64(pa) * 255 * af
				sg += float64(pg) / float64(pa) * 255 * af
				sb += float64(pb) / float64(pa) * 255 * af
			}
			sa += af
			n++
		}
	}
	if sa == 0 {
		return 0, 0, 0, 0
	}
	return sr / sa, sg / sa, sb / sa, sa / n
}

// classify picks pixelTransparent (below alphaThreshold coverage) or
// whichever of pixelDark/pixelLight the averaged r/g/b is nearer to by
// squared Euclidean distance.
func classify(r, g, bl, a float64) byte {
	if a < alphaThreshold {
		return pixelTransparent
	}
	dark := sqDist(r, g, bl, logoColorDarkR, logoColorDarkG, logoColorDarkB)
	light := sqDist(r, g, bl, logoColorLightR, logoColorLightG, logoColorLightB)
	if dark < light {
		return pixelDark
	}
	return pixelLight
}

func sqDist(r, g, b float64, r2, g2, b2 int) float64 {
	dr, dg, db := r-float64(r2), g-float64(g2), b-float64(b2)
	return dr*dr + dg*dg + db*db
}

func writeStringSlice(out *bytes.Buffer, name string, rows []string) {
	fmt.Fprintf(out, "var %s = []string{\n", name)
	for _, row := range rows {
		fmt.Fprintf(out, "\t%q,\n", row)
	}
	fmt.Fprint(out, "}\n\n")
}
