// Code generated by go:generate from assets/liam.png; DO NOT EDIT.

package tui

// logoTop and logoBottom are liam's block-art logo (issue #169), decoded
// from assets/liam.png by gen_logo.go. Each string is one terminal row's
// fixed-width sequence of logoPixel classifications (see logo.go), top and
// bottom paired per half-block character cell.
var logoTop = []string{
	"                    ",
	"                    ",
	"      DDLLLLDDD     ",
	"      DLLLLLLD      ",
	"       LLLLLLL      ",
	"       LLDDLL       ",
	"      LLLDDLLL      ",
	"                    ",
	"                    ",
}

var logoBottom = []string{
	"                    ",
	"                    ",
	"     DDLLLLLLLD     ",
	"       LDLLDLL      ",
	"       LLLLLLD      ",
	"       LLDDDLD      ",
	"       LL  LL       ",
	"                    ",
	"                    ",
}
